/* AUTO-GENERATED by build.py - DO NOT EDIT.
   Edit the matching *-content.json file and media folder,
   then run:  python3 build.py  */
window.EVENTS = [
  {
    "slug": "seehorse-florida",
    "title": "SeeHorse Florida",
    "status": "Past Event",
    "dateLabel": "Florida · Past Retreat",
    "location": "Florida",
    "summary": "The first SeeHorse gathering brought the circle into motion: horses, facilitators, sound, art, conversation, and a field of people learning how to listen together.",
    "body": [
      "In Florida, the first SeeHorse gathering unfolded from first light through golden hour. The horses set the pace as sound, stillness, conversation, and creative practice opened a field of shared attention.",
      "What emerged was less a program than a living exchange: practitioners and participants listening across disciplines, allowing the rhythm of the herd and the character of the land to guide the work."
    ],
    "details": [
      {
        "label": "Format",
        "value": "Retreat · Gallery · Field Notes"
      },
      {
        "label": "State",
        "value": "Archive"
      }
    ],
    "featured": true,
    "ctaLabel": "",
    "ctaUrl": "",
    "order": 0,
    "portrait": "media/events/seehorse-florida/gallery/01-first-light.jpg",
    "gallery": [
      "media/events/seehorse-florida/gallery/01-first-light.jpg",
      "media/events/seehorse-florida/gallery/02-the-circle-gathers.jpg",
      "media/events/seehorse-florida/gallery/03-stillness.jpg",
      "media/events/seehorse-florida/gallery/04-sound-and-silence.jpg",
      "media/events/seehorse-florida/gallery/05-the-conversation.jpg",
      "media/events/seehorse-florida/gallery/06-golden-hour.jpg"
    ]
  },
  {
    "slug": "noble-farm-retreat",
    "title": "Noble Farm Retreat",
    "status": "Upcoming",
    "dateLabel": "Newbury, Ohio · By Inquiry",
    "location": "Noble Farm",
    "summary": "A Heard2Herd gathering at Noble Farm, shaped around the herd, the land, and the people called into the work.",
    "body": [
      "At Noble Farm, the gathering will move at the pace of the horses and the land. Time for reflection, skilled practice, conversation, and quiet observation will create room for connection without forcing an outcome.",
      "Further details will be shared as the circle takes shape. Inquiries are welcome from those who feel drawn to the work."
    ],
    "details": [
      {
        "label": "Format",
        "value": "Retreat"
      },
      {
        "label": "State",
        "value": "Upcoming"
      }
    ],
    "featured": false,
    "ctaLabel": "Inquire",
    "ctaUrl": "mailto:",
    "order": 1,
    "portrait": "media/events/noble-farm-retreat/gallery/noble-farm-field.jpg",
    "gallery": [
      "media/events/noble-farm-retreat/gallery/noble-farm-field.jpg"
    ]
  }
];
