/* AUTO-GENERATED by build.py - DO NOT EDIT.
   Edit the matching *-content.json file and media folder,
   then run:  python3 build.py  */
window.EVENTS = [
  {
    "slug": "seehorse-florida",
    "title": "SeeHorse Florida",
    "status": "Past Event",
    "dateLabel": "Florida · Past Retreat",
    "location": "Florida",
    "summary": "The first SeeHorse gathering brought the circle into motion: horses, facilitators, sound, art, conversation, and a field of people learning how to listen together.",
    "body": [
      "This event page is a placeholder story container for the Florida SeeHorse retreat. The image sequence currently comes from the homepage Events gallery: first light, the circle gathering, stillness, sound and silence, conversation, and golden hour.",
      "Use this page for the event writeup, facilitator notes, participant reflections, location context, and a full gallery of the retreat as the archive grows."
    ],
    "details": [
      {
        "label": "Format",
        "value": "Retreat · Gallery · Field Notes"
      },
      {
        "label": "State",
        "value": "Archive"
      }
    ],
    "featured": true,
    "ctaLabel": "",
    "ctaUrl": "",
    "order": 0,
    "portrait": "media/events/seehorse-florida/gallery/01-first-light.jpg",
    "gallery": [
      "media/events/seehorse-florida/gallery/01-first-light.jpg",
      "media/events/seehorse-florida/gallery/02-the-circle-gathers.jpg",
      "media/events/seehorse-florida/gallery/03-stillness.jpg",
      "media/events/seehorse-florida/gallery/04-sound-and-silence.jpg",
      "media/events/seehorse-florida/gallery/05-the-conversation.jpg",
      "media/events/seehorse-florida/gallery/06-golden-hour.jpg"
    ]
  },
  {
    "slug": "noble-farm-retreat",
    "title": "Noble Farm Retreat",
    "status": "Upcoming",
    "dateLabel": "Newbury, Ohio · Date TBD",
    "location": "Noble Farm",
    "summary": "A future Heard2Herd gathering at Noble Farm, shaped around the herd, the land, and the people called into the work.",
    "body": [
      "This is a placeholder for an upcoming retreat. Add schedule, registration details, facilitator lineup, and imagery when the event is ready to announce."
    ],
    "details": [
      {
        "label": "Format",
        "value": "Retreat"
      },
      {
        "label": "State",
        "value": "Upcoming"
      }
    ],
    "featured": false,
    "ctaLabel": "Inquire",
    "ctaUrl": "mailto:",
    "order": 1,
    "portrait": null,
    "gallery": []
  }
];
