/* AUTO-GENERATED by build.py - DO NOT EDIT.
   Edit the matching *-content.json file and media folder,
   then run:  python3 build.py  */
window.HERD = [
  {
    "slug": "lee",
    "barnName": "Lee",
    "registeredName": "GV Lee of Noble Farm",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "PLACEHOLDER BIO — replace with Lee's real story. Lee is one of the founding members of the Noble Farm herd: a Gypsy Vanner whose steadiness anchors the group and sets the tempo for everyone around him.",
      "Known for his heavy feathering and an unflappable temperament, Lee is often the first to greet visitors at the gate and the last to leave it. Swap this text, his registered name, his photos, and his pedigree whenever you're ready."
    ],
    "order": 0,
    "featured": true,
    "portrait": "media/herd/lee/gallery/01.jpg",
    "gallery": [
      "media/herd/lee/gallery/01.jpg",
      "media/herd/lee/gallery/02.jpg",
      "media/herd/lee/gallery/03.jpg",
      "media/herd/lee/gallery/Day01_IMG_0098.jpg",
      "media/herd/lee/gallery/Day01_IMG_0101.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/lee/pedigree.pdf"
  },
  {
    "slug": "michael",
    "barnName": "Michael",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 1,
    "featured": true,
    "portrait": "media/herd/michael/gallery/01.jpg",
    "gallery": [
      "media/herd/michael/gallery/01.jpg",
      "media/herd/michael/gallery/Day02_IMG_0008.jpg",
      "media/herd/michael/gallery/Day02_IMG_0017.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "charm",
    "barnName": "Charm",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 2,
    "featured": true,
    "portrait": "media/herd/charm/gallery/01.jpg",
    "gallery": [
      "media/herd/charm/gallery/01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bumble",
    "barnName": "Bumble",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 3,
    "featured": false,
    "portrait": "media/herd/bumble/gallery/IMG_0446_Day02.jpg",
    "gallery": [
      "media/herd/bumble/gallery/IMG_0446_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0447_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0457_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0467_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0468_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0477_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0478_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0480_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0483_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0484_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0489_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0503_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0504_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0506_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0508_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0509_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0517_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bonslee",
    "barnName": "Bonslee",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 4,
    "featured": true,
    "portrait": "media/herd/bonslee/gallery/01.jpg",
    "gallery": [
      "media/herd/bonslee/gallery/01.jpg",
      "media/herd/bonslee/gallery/Day01_IMG_0059.jpg",
      "media/herd/bonslee/gallery/Day01_IMG_0067.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "lucky",
    "barnName": "Lucky",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 5,
    "featured": false,
    "portrait": "media/herd/lucky/gallery/IMG_0695_Day02.jpg",
    "gallery": [
      "media/herd/lucky/gallery/IMG_0695_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0698_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0705_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0711_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0724_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0726_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0727_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0729_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0732_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0746_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0775_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0781_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0795_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0824_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0838_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0842_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0846_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0849_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0855_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0871_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bruno",
    "barnName": "Bruno",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 6,
    "featured": false,
    "portrait": "media/herd/bruno/gallery/IMG_0517_Day02.jpg",
    "gallery": [
      "media/herd/bruno/gallery/IMG_0517_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0518_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0523_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0526_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0528_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0530_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0533_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0558_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0567_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0569_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0578_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0584_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0615_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0631_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0633_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0640_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0644_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0646_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0654_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0667_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0668_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0683_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0684_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0685_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0686_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0687_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "whiskers",
    "barnName": "Whiskers",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 7,
    "featured": false,
    "portrait": null,
    "gallery": [],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bentley",
    "barnName": "Bentley",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 8,
    "featured": false,
    "portrait": null,
    "gallery": [],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bonnie",
    "barnName": "Bonnie",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 9,
    "featured": false,
    "portrait": "media/herd/bonnie/gallery/IMG_0376_Day02.jpg",
    "gallery": [
      "media/herd/bonnie/gallery/IMG_0376_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0378_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0387_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0402_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0404_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0406_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0420_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0421_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0423_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0424_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0427_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "lizzie",
    "barnName": "Lizzie",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 10,
    "featured": false,
    "portrait": "media/herd/lizzie/gallery/IMG_0210_Day01.jpg",
    "gallery": [
      "media/herd/lizzie/gallery/IMG_0210_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0212_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0229_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0230_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0232_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0243_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0247_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0250_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0251_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0255_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0256_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0258_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0269_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0270_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0271_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "saoirse",
    "barnName": "Saoirse",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 11,
    "featured": false,
    "portrait": "media/herd/saoirse/gallery/IMG_0300_Day01.jpg",
    "gallery": [
      "media/herd/saoirse/gallery/IMG_0300_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0309_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0342_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0367_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0373_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0397_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0407_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0409_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0451_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0452_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0459_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0463_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "punkn",
    "barnName": "Punkn",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 12,
    "featured": false,
    "portrait": null,
    "gallery": [],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "tuesday",
    "barnName": "Tuesday",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 13,
    "featured": false,
    "portrait": null,
    "gallery": [],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "smudge",
    "barnName": "Smudge",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 14,
    "featured": false,
    "portrait": "media/herd/smudge/gallery/IMG_0246_Day02.jpg",
    "gallery": [
      "media/herd/smudge/gallery/IMG_0246_Day02.jpg",
      "media/herd/smudge/gallery/IMG_0282_Day02.jpg",
      "media/herd/smudge/gallery/IMG_0291_Day02.jpg",
      "media/herd/smudge/gallery/IMG_0332_Day02.jpg",
      "media/herd/smudge/gallery/IMG_0347_Day02.jpg",
      "media/herd/smudge/gallery/IMG_0353_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "madge",
    "barnName": "Madge",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 15,
    "featured": false,
    "portrait": "media/herd/madge/gallery/IMG_0464_Day01.jpg",
    "gallery": [
      "media/herd/madge/gallery/IMG_0464_Day01.jpg",
      "media/herd/madge/gallery/IMG_0469_Day01.jpg",
      "media/herd/madge/gallery/IMG_0473_Day01.jpg",
      "media/herd/madge/gallery/IMG_0475_Day01.jpg",
      "media/herd/madge/gallery/IMG_0483_Day01.jpg",
      "media/herd/madge/gallery/IMG_0484_Day01.jpg",
      "media/herd/madge/gallery/IMG_0492_Day01.jpg",
      "media/herd/madge/gallery/IMG_0495_Day01.jpg",
      "media/herd/madge/gallery/IMG_0498_Day01.jpg",
      "media/herd/madge/gallery/IMG_0507_Day01.jpg",
      "media/herd/madge/gallery/IMG_0509_Day01.jpg",
      "media/herd/madge/gallery/IMG_0520_Day01.jpg",
      "media/herd/madge/gallery/IMG_0523_Day01.jpg",
      "media/herd/madge/gallery/IMG_0525_Day01.jpg",
      "media/herd/madge/gallery/IMG_0528_Day01.jpg",
      "media/herd/madge/gallery/IMG_0531_Day01.jpg",
      "media/herd/madge/gallery/IMG_0533_Day01.jpg",
      "media/herd/madge/gallery/IMG_0535_Day01.jpg",
      "media/herd/madge/gallery/IMG_0536_Day01.jpg",
      "media/herd/madge/gallery/IMG_0537_Day01.jpg",
      "media/herd/madge/gallery/IMG_0538_Day01.jpg",
      "media/herd/madge/gallery/IMG_0540_Day01.jpg",
      "media/herd/madge/gallery/IMG_0542_Day01.jpg",
      "media/herd/madge/gallery/IMG_0548_Day01.jpg",
      "media/herd/madge/gallery/IMG_0554_Day01.jpg",
      "media/herd/madge/gallery/IMG_0556_Day01.jpg",
      "media/herd/madge/gallery/IMG_0565_Day01.jpg",
      "media/herd/madge/gallery/IMG_0567_Day01.jpg",
      "media/herd/madge/gallery/IMG_0569_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "luna",
    "barnName": "Luna",
    "registeredName": "",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Profile coming soon — bio, registered name, photos, and pedigree will live here."
    ],
    "order": 16,
    "featured": false,
    "portrait": "media/herd/luna/gallery/IMG_0105_Day01.jpg",
    "gallery": [
      "media/herd/luna/gallery/IMG_0105_Day01.jpg",
      "media/herd/luna/gallery/IMG_0108_Day01.jpg",
      "media/herd/luna/gallery/IMG_0110_Day01.jpg",
      "media/herd/luna/gallery/IMG_0128_Day01.jpg",
      "media/herd/luna/gallery/IMG_0146_Day01.jpg",
      "media/herd/luna/gallery/IMG_0149_Day01.jpg",
      "media/herd/luna/gallery/IMG_0151_Day01.jpg",
      "media/herd/luna/gallery/IMG_0154_Day01.jpg",
      "media/herd/luna/gallery/IMG_0157_Day01.jpg",
      "media/herd/luna/gallery/IMG_0160_Day01.jpg",
      "media/herd/luna/gallery/IMG_0167_Day01.jpg",
      "media/herd/luna/gallery/IMG_0169_Day01.jpg",
      "media/herd/luna/gallery/IMG_0176_Day01.jpg",
      "media/herd/luna/gallery/IMG_0186_Day01.jpg",
      "media/herd/luna/gallery/IMG_0188_Day01.jpg",
      "media/herd/luna/gallery/IMG_0189_Day01.jpg",
      "media/herd/luna/gallery/IMG_0192_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  }
];
