/* AUTO-GENERATED by build.py - DO NOT EDIT.
   Edit the matching *-content.json file and media folder,
   then run:  python3 build.py  */
window.HERD = [
  {
    "slug": "lee",
    "barnName": "Lee",
    "registeredName": "Parnell's Leannan",
    "birthYear": "2005",
    "sex": "Stallion",
    "bio": [
      "A distinguished Irish import, Lee boasts impeccable conformation, strong bone, and a glorious feather and coat. His refined presence and sure-footed versatility make him a natural in both riding and driving. At the ranch, Kim delights children with his almost mythical elegance, urging them to cherish the secret of this living unicorn."
    ],
    "order": 0,
    "featured": true,
    "portrait": "media/herd/lee/gallery/01.jpg",
    "gallery": [
      "media/herd/lee/gallery/01.jpg",
      "media/herd/lee/gallery/Day01_IMG_0098.jpg",
      "media/herd/lee/gallery/Day01_IMG_0101.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/lee/pedigree.pdf"
  },
  {
    "slug": "michael",
    "barnName": "Michael",
    "registeredName": "Parnell's Skellig Michael",
    "birthYear": "2015",
    "sex": "Stallion",
    "bio": [
      "Playful, joyful, and impeccably balanced, Michael combines intelligence with an interactive spirit. His versatility shines in both riding and driving, tackling swift river crossings and steep terrain with fearless confidence. Every movement is a study in graceful power."
    ],
    "order": 1,
    "featured": true,
    "portrait": "media/herd/michael/gallery/01.jpg",
    "gallery": [
      "media/herd/michael/gallery/01.jpg",
      "media/herd/michael/gallery/Day02_IMG_0008.jpg",
      "media/herd/michael/gallery/Day02_IMG_0017.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/michael/pedigree.pdf"
  },
  {
    "slug": "charm",
    "barnName": "Charm",
    "registeredName": "",
    "birthYear": "",
    "sex": "Gelding",
    "bio": [
      "Patient and exceptionally kind, Charm exudes a gentle, stoic demeanor backed by a sensitive nature. He thrives as a nurturing herd nanny, guiding young horses toward independence with patient boundaries, often tending to them with a loving lick. His floaty gait adds an effortless elegance."
    ],
    "order": 2,
    "featured": true,
    "portrait": "media/herd/charm/gallery/01.jpg",
    "gallery": [
      "media/herd/charm/gallery/01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bumble",
    "barnName": "Bumble",
    "registeredName": "Bumble Bee Bon",
    "birthYear": "2018",
    "sex": "Gelding",
    "bio": [
      "Bumble, the first foal of the season, arrived amid a playful nighttime adventure that saw his sire Lee and dam Bonnie briefly escape the pasture. This solid bay displays a luminous, dappled coat and a relaxed, exploratory spirit. He delights in open-air rides, embodying laid-back confidence."
    ],
    "order": 3,
    "featured": false,
    "portrait": "media/herd/bumble/gallery/1.jpg",
    "gallery": [
      "media/herd/bumble/gallery/1.jpg",
      "media/herd/bumble/gallery/IMG_0446_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0447_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0457_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0467_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0468_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0477_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0478_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0480_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0483_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0484_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0503_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0504_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0506_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0508_Day02.jpg",
      "media/herd/bumble/gallery/IMG_0509_Day02.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/bumble/pedigree.pdf"
  },
  {
    "slug": "bonslee",
    "barnName": "Bonslee",
    "registeredName": "Bonslee Bok",
    "birthYear": "2020",
    "sex": "Gelding",
    "bio": [
      "Bonslee radiates a charismatic presence, greeting every visitor at the gate with unmistakable main-character energy. Loyal and personable, he follows closely during pen cleaning and embraces every new challenge with bold bravery. His spirited disposition ensures fun at every turn."
    ],
    "order": 4,
    "featured": true,
    "portrait": "media/herd/bonslee/gallery/01.jpg",
    "gallery": [
      "media/herd/bonslee/gallery/01.jpg",
      "media/herd/bonslee/gallery/IMG_0246_Day02.jpg",
      "media/herd/bonslee/gallery/IMG_0282_Day02.jpg",
      "media/herd/bonslee/gallery/IMG_0291_Day02.jpg",
      "media/herd/bonslee/gallery/IMG_0332_Day02.jpg",
      "media/herd/bonslee/gallery/IMG_0347_Day02.jpg",
      "media/herd/bonslee/gallery/IMG_0353_Day02.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/bonslee/pedigree.pdf"
  },
  {
    "slug": "lucky",
    "barnName": "Lucky",
    "registeredName": "",
    "birthYear": "",
    "sex": "Gelding",
    "bio": [
      "Lucky, a striking gelding with unique coloring, exudes an innate people-oriented charm. He delights in building connections, eagerly responding to human cues and thriving in interactive settings. His confident bearing and easygoing nature make him a favorite among visitors."
    ],
    "order": 5,
    "featured": false,
    "portrait": "media/herd/lucky/gallery/1.jpg",
    "gallery": [
      "media/herd/lucky/gallery/1.jpg",
      "media/herd/lucky/gallery/2.jpg",
      "media/herd/lucky/gallery/IMG_0695_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0698_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0705_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0711_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0724_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0726_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0727_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0732_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0746_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0775_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0781_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0824_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0838_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0842_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0846_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0849_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0855_Day02.jpg",
      "media/herd/lucky/gallery/IMG_0871_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bruno",
    "barnName": "Bruno",
    "registeredName": "",
    "birthYear": "",
    "sex": "Gelding",
    "bio": [
      "Bruno, a thoughtful gelding, possesses a deep intuitive awareness that sets him apart. His reflective nature translates into a calm, steady presence and measured precision in movement. With a strong yet gentle disposition, Bruno exudes reliability and a nuanced understanding of his surroundings."
    ],
    "order": 6,
    "featured": false,
    "portrait": "media/herd/bruno/gallery/2.jpg",
    "gallery": [
      "media/herd/bruno/gallery/2.jpg",
      "media/herd/bruno/gallery/3.jpg",
      "media/herd/bruno/gallery/4.jpg",
      "media/herd/bruno/gallery/5.jpg",
      "media/herd/bruno/gallery/6.jpg",
      "media/herd/bruno/gallery/IMG_0517_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0518_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0523_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0526_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0528_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0530_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0533_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0558_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0567_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0569_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0584_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0615_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0633_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0640_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0644_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0654_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0667_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0668_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0683_Day02.jpg",
      "media/herd/bruno/gallery/IMG_0684_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "whiskers",
    "barnName": "Whiskas",
    "registeredName": "",
    "birthYear": "",
    "sex": "Colt (Yearling)",
    "bio": [
      "Whiskas radiates a friendly temperament that endears him to all who meet him. His soft, approachable demeanor pairs with an athletic build. As he matures, Whiskas is poised to develop into a versatile and amiable partner, ready for both training and leisurely rides."
    ],
    "order": 7,
    "featured": false,
    "portrait": "media/herd/whiskers/gallery/01.jpg",
    "gallery": [
      "media/herd/whiskers/gallery/01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bentley",
    "barnName": "Bentley",
    "registeredName": "",
    "birthYear": "",
    "sex": "Colt (Foal)",
    "bio": [
      "Bentley, a fresh-born colt, instantly captured attention with his inquisitive eyes and playful disposition. Though still tender, his silky coat and graceful gait hint at a promising future. Curious and eager to explore, Bentley thrives on human interaction, already displaying a keen intelligence."
    ],
    "order": 8,
    "featured": false,
    "portrait": "media/herd/bentley/gallery/01.jpg",
    "gallery": [
      "media/herd/bentley/gallery/01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "bonnie",
    "barnName": "Bonnie",
    "registeredName": "",
    "birthYear": "",
    "sex": "Mare",
    "bio": [
      "An Irish-bred beauty, Bonnie carries a distinguished lineage marked by boldness and courage. Her striking conformation and regal presence make her a standout in the paddock, while her nurturing nature shines as an exemplary dam."
    ],
    "order": 9,
    "featured": false,
    "portrait": "media/herd/bonnie/gallery/IMG_0376_Day02.jpg",
    "gallery": [
      "media/herd/bonnie/gallery/IMG_0376_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0378_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0387_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0402_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0404_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0406_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0420_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0421_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0423_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0424_Day02.jpg",
      "media/herd/bonnie/gallery/IMG_0427_Day02.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "lizzie",
    "barnName": "Lizzie",
    "registeredName": "",
    "birthYear": "",
    "sex": "Mare",
    "bio": [
      "An Irish import of regal lineage, Lizzie presents flawless conformation and an air of aristocratic poise. Highly skilled under harness and eager under saddle, she connects deeply with her rider, delivering heartful performance with unwavering dedication."
    ],
    "order": 10,
    "featured": false,
    "portrait": "media/herd/lizzie/gallery/1.jpg",
    "gallery": [
      "media/herd/lizzie/gallery/1.jpg",
      "media/herd/lizzie/gallery/IMG_0210_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0212_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0229_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0230_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0232_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0243_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0247_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0250_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0251_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0255_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0256_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0258_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0269_Day01.jpg",
      "media/herd/lizzie/gallery/IMG_0271_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "saoirse",
    "barnName": "Saoirse",
    "registeredName": "Parnell's Saoirse",
    "birthYear": "2015",
    "sex": "Mare",
    "bio": [
      "Named for independence and liberty, Saoirse offers a sweet, captivating presence. Small in stature yet boasting a magnificent mane and generous heart, she balances elegance with a gentle temperament."
    ],
    "order": 11,
    "featured": false,
    "portrait": "media/herd/saoirse/gallery/IMG_0300_Day01.jpg",
    "gallery": [
      "media/herd/saoirse/gallery/IMG_0300_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0309_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0342_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0367_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0373_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0397_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0407_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0409_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0451_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0452_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0459_Day01.jpg",
      "media/herd/saoirse/gallery/IMG_0463_Day01.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/saoirse/pedigree.pdf"
  },
  {
    "slug": "punkn",
    "barnName": "Punkn",
    "registeredName": "Punk N' Spice",
    "birthYear": "2016",
    "sex": "Mare",
    "bio": [
      "Punkn, a spirited mare, blends sweetness with an unmistakable spunk. Her kind heart and good-minded nature make her a cherished companion, while her robust maternal instincts have already shone through as an attentive mother. With her beautiful painted coat and graceful movement, she offers both elegance and an adventurous spirit."
    ],
    "order": 12,
    "featured": false,
    "portrait": "media/herd/punkn/gallery/1.jpg",
    "gallery": [
      "media/herd/punkn/gallery/1.jpg",
      "media/herd/punkn/gallery/IMG_0695_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0698_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0705_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0711_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0724_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0726_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0727_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0729_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0732_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0746_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0775_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0795_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0824_Day02.jpg",
      "media/herd/punkn/gallery/IMG_0838_Day02.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/punkn/pedigree.pdf"
  },
  {
    "slug": "tuesday",
    "barnName": "Tuesday",
    "registeredName": "Morning's Chance at Gold",
    "birthYear": "2012",
    "sex": "Mare",
    "bio": [
      "At a graceful 15.1 hands, Tuesday blends a kitten-like personality with refined beauty. Her rare bay hue and delicate feminine features complement a poised, elegant stride."
    ],
    "order": 13,
    "featured": false,
    "portrait": "media/herd/tuesday/gallery/1.jpg",
    "gallery": [
      "media/herd/tuesday/gallery/1.jpg",
      "media/herd/tuesday/gallery/2.jpg",
      "media/herd/tuesday/gallery/3.jpg",
      "media/herd/tuesday/gallery/4.jpg",
      "media/herd/tuesday/gallery/IMG_0517_Day02 2.jpg",
      "media/herd/tuesday/gallery/IMG_0518_Day02.jpg",
      "media/herd/tuesday/gallery/IMG_0615_Day02.jpg",
      "media/herd/tuesday/gallery/IMG_0668_Day02.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/tuesday/pedigree.pdf"
  },
  {
    "slug": "smudge",
    "barnName": "Smudge",
    "registeredName": "Smudge of Gold",
    "birthYear": "2010",
    "sex": "Mare",
    "bio": [
      "Smudge, a true embodiment of beauty, was Kim's first horse and exemplifies meticulous care for her rider. She revels in grooming and pampering, delivering soulful performances that reflect depth and elegance."
    ],
    "order": 14,
    "featured": false,
    "portrait": "media/herd/smudge/gallery/1.jpg",
    "gallery": [
      "media/herd/smudge/gallery/1.jpg",
      "media/herd/smudge/gallery/2.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/smudge/pedigree.pdf"
  },
  {
    "slug": "madge",
    "barnName": "Madge",
    "registeredName": "",
    "birthYear": "",
    "sex": "Mare",
    "bio": [
      "Madge exudes curiosity and fun, always the first to notice change and investigate. Her friendly disposition makes her a cherished companion."
    ],
    "order": 15,
    "featured": false,
    "portrait": "media/herd/madge/gallery/1.jpg",
    "gallery": [
      "media/herd/madge/gallery/1.jpg",
      "media/herd/madge/gallery/2.jpg",
      "media/herd/madge/gallery/3.jpg",
      "media/herd/madge/gallery/4.jpg",
      "media/herd/madge/gallery/IMG_0469_Day01.jpg",
      "media/herd/madge/gallery/IMG_0473_Day01.jpg",
      "media/herd/madge/gallery/IMG_0475_Day01.jpg",
      "media/herd/madge/gallery/IMG_0483_Day01.jpg",
      "media/herd/madge/gallery/IMG_0484_Day01.jpg",
      "media/herd/madge/gallery/IMG_0492_Day01.jpg",
      "media/herd/madge/gallery/IMG_0495_Day01.jpg",
      "media/herd/madge/gallery/IMG_0498_Day01.jpg",
      "media/herd/madge/gallery/IMG_0507_Day01.jpg",
      "media/herd/madge/gallery/IMG_0520_Day01.jpg",
      "media/herd/madge/gallery/IMG_0523_Day01.jpg",
      "media/herd/madge/gallery/IMG_0525_Day01.jpg",
      "media/herd/madge/gallery/IMG_0528_Day01.jpg",
      "media/herd/madge/gallery/IMG_0533_Day01.jpg",
      "media/herd/madge/gallery/IMG_0535_Day01.jpg",
      "media/herd/madge/gallery/IMG_0536_Day01.jpg",
      "media/herd/madge/gallery/IMG_0537_Day01.jpg",
      "media/herd/madge/gallery/IMG_0538_Day01.jpg",
      "media/herd/madge/gallery/IMG_0540_Day01.jpg",
      "media/herd/madge/gallery/IMG_0542_Day01.jpg",
      "media/herd/madge/gallery/IMG_0548_Day01.jpg",
      "media/herd/madge/gallery/IMG_0554_Day01.jpg",
      "media/herd/madge/gallery/IMG_0556_Day01.jpg",
      "media/herd/madge/gallery/IMG_0565_Day01.jpg",
      "media/herd/madge/gallery/IMG_0567_Day01.jpg"
    ],
    "hasPedigree": false,
    "pedigree": null
  },
  {
    "slug": "luna",
    "barnName": "Luna",
    "registeredName": "Luna LeeDay",
    "birthYear": "2020",
    "sex": "Mare",
    "bio": [
      "Luna's registered name evokes a showgirl's charisma; her striking gray dapples and lofty presence command attention. Intelligent, sensitive, and intuitively eager to please, she consistently delivers smooth, graceful gaits."
    ],
    "order": 16,
    "featured": false,
    "portrait": "media/herd/luna/gallery/1.jpg",
    "gallery": [
      "media/herd/luna/gallery/1.jpg",
      "media/herd/luna/gallery/2.jpg",
      "media/herd/luna/gallery/3.jpg",
      "media/herd/luna/gallery/4.jpg",
      "media/herd/luna/gallery/5.jpg",
      "media/herd/luna/gallery/6.jpg",
      "media/herd/luna/gallery/IMG_0105_Day01.jpg",
      "media/herd/luna/gallery/IMG_0108_Day01.jpg",
      "media/herd/luna/gallery/IMG_0110_Day01.jpg",
      "media/herd/luna/gallery/IMG_0128_Day01.jpg",
      "media/herd/luna/gallery/IMG_0149_Day01.jpg",
      "media/herd/luna/gallery/IMG_0151_Day01.jpg",
      "media/herd/luna/gallery/IMG_0154_Day01.jpg",
      "media/herd/luna/gallery/IMG_0157_Day01.jpg",
      "media/herd/luna/gallery/IMG_0160_Day01.jpg",
      "media/herd/luna/gallery/IMG_0167_Day01.jpg",
      "media/herd/luna/gallery/IMG_0186_Day01.jpg"
    ],
    "hasPedigree": true,
    "pedigree": "media/herd/luna/pedigree.pdf"
  }
];
