/* AUTO-GENERATED by build.py - DO NOT EDIT.
   Edit the matching *-content.json file and media folder,
   then run:  python3 build.py  */
window.PEOPLE = [
  {
    "slug": "kimberly-pezzeminti",
    "displayName": "Kimberly Pezzeminti",
    "footerName": "Kimberly Pezzeminti",
    "role": "Artist · Writer · Creative Seeker",
    "eyebrow": "The Circle",
    "bio": [
      "Kim creates spaces--both literal and unseen--where transformation unfolds naturally. From her work in the tile industry, collaborating with artisans, designers, educators, and marketing professionals to bring singular visions to life, to owning and stewarding a ranch in Meeteetse, Wyoming, Kim is driven by a deep curiosity about what becomes possible when people, place, and purpose meet. Her work with Gypsy Vanner horses is another expression of this calling: designing experiences that invite unexpected, often life-changing, connection.",
      "In alignment with this vision, Zingara Farms in Florida is both land and sanctuary--a place where nature, human connection, and healing come together.",
      "Kim's superpower is her ability to see the invisible threads guiding people toward their next chapter, and to weave those threads with intention, authenticity, and trust in what emerges when the right elements align.",
      "This retreat is a culmination of Kim's journey rooted in truth and trust. It reflects her distilled approach: bringing together accomplished practitioners from diverse disciplines, remarkable horses known for their intuitive nature, and people who feel the pull toward something meaningful--even if they can't yet name it."
    ],
    "order": 0,
    "featured": true,
    "website": "",
    "instagram": "https://www.instagram.com/heard2herd/",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Kim's practice lives at the meeting point of place, purpose, and transformation: designing environments where people, horses, land, and creative work can meet with intention."
      },
      {
        "title": "Portfolio",
        "body": "A home for retreat documentation, writing, Heard2Herd imagery, ranch and sanctuary work, and Kimberly's evolving creative field."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "amy-lundahl",
    "displayName": "Amy Lundahl",
    "footerName": "Amy Lundahl",
    "role": "Horsewoman · Teacher · Noble Farm",
    "eyebrow": "The Circle",
    "bio": [
      "Amy has mastered the applied art of presence, rhythm, timing, and energy with horses. As a professional horsewoman and co-owner of Noble Farm in Newbury, Ohio, her work centers on guiding others into a world where human striving and overthinking must yield to a more immediate, instinctual existence.",
      "Amy believes that horses offer us depth, understanding, and enjoyment that extends far beyond simply learning to ride. Horsemanship challenges us to communicate through body language, feel, and purposeful cycles of movement and stillness. It also broadens our awareness, as we must interpret the immediate feedback from an animal who responds only to our true signal. Amy specializes in teaching the mechanics of congruent communication between humans and horses. She translates this invisible language until belief, intention, and action finally align and mechanics dissolve into embodied fluency.",
      "Cowgirl, farmhand, businesswoman, and mother are just a few of the hats Amy has worn on her journey. She spent years on working ranches across Texas, Wyoming, and Nebraska, starting colts, managing cattle, and training horses. She lived and worked in places where the land and livestock respond to what you are, not what you say. Those experiences built the foundation of her training and communication style today."
    ],
    "order": 1,
    "featured": true,
    "website": "https://www.lundahlperformance.com",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Amy teaches the mechanics of congruent communication: presence, timing, feel, and the embodied language that lets belief, intention, and action align around horses."
      },
      {
        "title": "Portfolio",
        "body": "A place for Noble Farm work, horsemanship teaching, clinic documentation, ranch experience, and moments of horse-human communication."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "lesley-turski",
    "displayName": "Lesley Turski",
    "footerName": "Lesley Turski",
    "role": "Sound Healing · Biofield Tuning",
    "eyebrow": "The Circle",
    "bio": [
      "Lesley Turski is the founder of Cleveland Sound Healing. With over fifteen years of experience in healthcare and a background in psychology, she brings a calm, supportive, and heart-centered approach to her work. She uses vibrational sound to help people reconnect with their vitality and find a greater sense of ease.",
      "Her work is science-based and grounded in how sound and vibration affect the nervous system. Through frequency and resonance, she gently supports the body in shifting out of stress and into a parasympathetic, rest-and-restore state. This can help relieve stress and tension, support mental clarity, and promote emotional balance.",
      "Using singing bowls, tuning forks, and other vibrational sound-healing instruments, Lesley creates space for deep relaxation and restoration, personalized to meet the specific needs of each individual or group. Her practice includes sound healing and Biofield Tuning for individuals, groups, and corporate wellness, offered in person, off-site, and remotely.",
      "She is honored to be part of this retreat and to offer sound as a gentle companion to reflection, connection, and restoration alongside the horses.",
      "Learn more about her offerings at www.clevelandsoundhealing.com."
    ],
    "order": 2,
    "featured": true,
    "website": "https://www.clevelandsoundhealing.com",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Lesley uses sound, vibration, frequency, and resonance to help the nervous system move toward rest, restoration, clarity, and emotional balance."
      },
      {
        "title": "Portfolio",
        "body": "A place for sound-healing sessions, Biofield Tuning offerings, instruments, retreat documentation, audio, and wellness work."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "sarah-scarborough",
    "displayName": "Sarah Scarborough",
    "footerName": "Sarah Scarborough",
    "role": "Tea Huntress · Ritual · Wellness",
    "eyebrow": "The Circle",
    "bio": [
      "From an early age, Sarah was drawn to the magic of plants. She spent summers with her maternal family in Finland, foraging healing herbs in the forest, which sparked a lifelong calling to live in close connection to nature.",
      "Her studies in sustainable agriculture took her to organic farms in California, Montana, Tennessee, and Connecticut. It was during her time as a cook at a Tibetan teahouse in Montana that tea found her.",
      "Since then, Sarah's exploration of the world of tea has taken her across the globe, working as a tea buyer, taster, and formulator for international brands. She has also founded multiple tea companies, combining her love of travel, agriculture, sustainability, and wellness. Her portfolio is a testament to her dedication to creating meaningful connections through tea.",
      "Tea Huntress has been both her muse and her guide, leading her toward becoming a strong and self-sufficient entrepreneur. Along the way, Sarah has embraced challenges, overcome self-doubt, and cultivated a supportive community of women who inspire and expand her vision.",
      "With a commitment to the power of calm, the wisdom of nature, and the transformative potential of tea, Tea Huntress inspires its clients to slow down and receive the healing benefits of tea. Sarah's vision is rooted in the belief that tea is more than a drink--it is a ritual of connection, stillness, and simplicity that nourishes the soul."
    ],
    "order": 3,
    "featured": true,
    "website": "",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Sarah's work centers tea as ritual: a practice of calm, plant wisdom, sustainability, stillness, and connection."
      },
      {
        "title": "Portfolio",
        "body": "A place for Tea Huntress work, tea sourcing, formulation, ritual design, travel, agriculture, and wellness documentation."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "tony-duncan",
    "displayName": "Tony Duncan",
    "footerName": "Tony Duncan",
    "role": "Songs · Stories · Dance",
    "eyebrow": "The Circle",
    "bio": [
      "Experience the rich culture of Native America through the songs, stories, and dances of Tony Duncan Productions. We dance to the four directions to share the stories of our ancestors. We sing songs of celebration as we honor the strength and beauty of our indigenous brothers and sisters. We gather around our elders and listen to the stories passed down from generation to generation.",
      "Filled with knowledge and wisdom, these stories of creation, warriors, and tricksters have captivated audiences far and wide. As we listen to the calling wind, we hear the melodies of the Native American flute. Songs of courtship, meditation, and healing are heard deep in the canyons of the Southwest.",
      "All of life dances in a sacred circle as a season gives way to the next. We sing, we dance, and we celebrate this journey called Life."
    ],
    "order": 4,
    "featured": true,
    "website": "",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Tony Duncan Productions shares Native American songs, stories, dances, flute melodies, and teachings carried through celebration and cultural memory."
      },
      {
        "title": "Portfolio",
        "body": "A place for performance documentation, music, storytelling, dance, flute work, video, and retreat offerings."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "sophia-duncan",
    "displayName": "Sophia Duncan",
    "footerName": "Sophia Duncan",
    "role": "Artist",
    "eyebrow": "The Circle",
    "bio": [
      "Sophia Duncan is an artist in the Heard2Herd circle. Full biography coming soon."
    ],
    "order": 5,
    "featured": true,
    "website": "",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "A placeholder for Sophia's artistic practice, process, influences, and creative work."
      },
      {
        "title": "Portfolio",
        "body": "A placeholder portfolio for Sophia's artwork, studio documentation, and selected pieces.",
        "images": [
          "media/people/sophia-duncan/gallery/01.jpeg",
          "media/people/sophia-duncan/gallery/02.jpeg"
        ]
      }
    ],
    "portrait": "media/people/sophia-duncan/gallery/01.jpeg",
    "gallery": [
      "media/people/sophia-duncan/gallery/01.jpeg",
      "media/people/sophia-duncan/gallery/02.jpeg"
    ]
  },
  {
    "slug": "nisha-manek",
    "displayName": "Nisha Manek, MD, FACP",
    "footerName": "Nisha Manek",
    "role": "Integrative Medicine · Information Medicine",
    "eyebrow": "The Circle",
    "bio": [
      "Nisha Manek is an internationally recognized leader in the field of integrative medicine. Nisha's humble background from Kenya propelled her to transcend limitations of gender, ethnicity, and financial status. From Case Western Reserve University in Cleveland, Ohio, where she graduated summa cum laude, to the University of Glasgow School of Medicine in Scotland, Nisha's uncommon tenacity has driven her to ask difficult questions and pursue answers beyond traditional medical paradigms.",
      "Nisha began her career in rheumatology at the Mayo Clinic in Rochester, Minnesota. Recognized as Teacher of the Year in the School of Medicine, she brings storytelling as a core skill to bedside medical teaching and on the plenary stage.",
      "But she didn't stop there. Nisha partnered with one of the world's most innovative physicists, Emeritus Professor William A. Tiller of Stanford University, and pushed the boundaries of what is possible in medicine. She is the preeminent doctor of information medicine, which intersects consciousness, biofield science, and rheumatology to improve human health.",
      "She has authored a one-of-a-kind book, Bridging Science and Spirit, which closes the gap between two seemingly separate areas of knowledge. She is a fellow of the American College of Physicians and a fellow of the Royal College of Physicians of the United Kingdom."
    ],
    "order": 6,
    "featured": true,
    "website": "",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Nisha's work bridges integrative medicine, rheumatology, consciousness, biofield science, and information medicine."
      },
      {
        "title": "Portfolio",
        "body": "A place for writing, talks, teaching, Bridging Science and Spirit, medical leadership, and retreat documentation."
      }
    ],
    "portrait": null,
    "gallery": []
  },
  {
    "slug": "laura-vanderberg",
    "displayName": "Laura Vanderberg, PhD, PCC, E-RYT 500",
    "footerName": "Laura Vanderberg",
    "role": "Leadership Development · Yoga Therapy",
    "eyebrow": "The Circle",
    "bio": [
      "Dr. Laura Vanderberg is a leadership development expert, yoga therapist, and retreat facilitator who unites the precision of science with the art of human development. With a PhD in microbiology from North Carolina State University and experience as a chief scientist leading complex research initiatives, Laura developed a systems-level understanding of how things grow, adapt, and thrive--whether in nature, organizations, or people.",
      "A Professional Certified Coach through the International Coaching Federation, with additional training from the Mayo Clinic in Health and Wellness Coaching, she now brings that same curiosity and structure to cultivating leadership, resilience, and collaboration in people and in organizations. Laura supports physicians, scientists, and senior leaders in integrating inner awareness with outer impact. Her work with the Northern Arizona VA Healthcare System, Lawrence Livermore National Laboratory, and other smaller technical organizations reflects her ability to translate evidence-based insight into experiences that foster both high performance and well-being.",
      "As an E-RYT 500 yoga instructor, yoga therapist, and former studio owner, Laura integrates breath, movement, mindfulness, and modern behavioral science to help people reconnect with vitality and presence. She has led retreats across the globe, from Iceland to the Galapagos, that offer space for reflection, restoration, and renewed purpose.",
      "Whether in a stressful office building or a mountain retreat, Laura invites participants to reconnect with their internal wisdom, restore balance, and reawaken purpose. What do people say about their experience? Time spent with Laura allows them to rest, reflect, and reawaken their capacity for balance, compassion, and joy--personally and professionally--so that they can meet the demands of their lives with more clarity."
    ],
    "order": 7,
    "featured": true,
    "website": "",
    "instagram": "",
    "links": [],
    "sections": [
      {
        "title": "Practice",
        "body": "Laura integrates leadership development, science, coaching, yoga therapy, breath, movement, mindfulness, and behavioral science."
      },
      {
        "title": "Portfolio",
        "body": "A place for retreats, coaching work, leadership development, yoga therapy, wellness programs, and facilitation documentation."
      }
    ],
    "portrait": null,
    "gallery": []
  }
];
